import {beforeEach,describe,it,expect,vi} from 'vitest';
const state=vi.hoisted(()=>({existing:null as any,writes:[] as Array<{table:string;kind:string;payload:any}>}));
vi.mock('../services/supabase',()=>({getSupabaseClient:()=>({from:(table:string)=>{
 let patch:any;
 const q:any={select:()=>q,ilike:()=>q,eq:()=>q,limit:()=>q,is:()=>q,insert:(payload:any)=>{patch=payload;state.writes.push({table,kind:'insert',payload});return q;},update:(payload:any)=>{patch=payload;state.writes.push({table,kind:'update',payload});return q;},upsert:(payload:any)=>{patch=payload;state.writes.push({table,kind:'upsert',payload});return q;},maybeSingle:async()=>({data:table==='outbound_businesses'?state.existing:null,error:null}),single:async()=>({data:{id:table,...patch},error:null}),then:(resolve:any)=>Promise.resolve({data:{id:table,...patch},error:null}).then(resolve)};return q;
}})}));
import {importOutboundBusinesses,importOutboundRows} from '../services/outboundRepository';
beforeEach(()=>{state.existing=null;state.writes=[];});
describe('explicit demo creation with safe future business defaults',()=>{
 it('explicitly enables only a newly created demo business from the business CSV',async()=>{await importOutboundBusinesses([{business_name:'New demo'} as any],false);expect(state.writes).toEqual([{table:'outbound_businesses',kind:'insert',payload:{business_name:'New demo',is_demo:true,outreach_enabled:true}}]);});
 it('does not re-enable an existing locked business when updating its CSV fields',async()=>{state.existing={id:'existing',business_name:'Existing demo',is_demo:true,outreach_enabled:false};await importOutboundBusinesses([{business_name:'Existing demo',industry:'elevator_inspection'} as any],false);expect(state.writes).toHaveLength(1);expect(state.writes[0].kind).toBe('update');expect(state.writes[0].payload).not.toHaveProperty('outreach_enabled');});
 it('explicitly enables only a newly created demo through the invoice CSV path',async()=>{await importOutboundRows([{business_name:'New invoice demo',external_customer_id:'fixture-customer',invoice_id:'fixture-invoice',amount_due_cents:10000,status:'unpaid'} as any],false);expect(state.writes.find(w=>w.table==='outbound_businesses'&&w.kind==='insert')?.payload).toEqual({business_name:'New invoice demo',industry:'elevator_inspection',is_demo:true,outreach_enabled:true});});
 it('does not change an existing business lock through an invoice import',async()=>{state.existing={id:'existing',business_name:'Existing demo',is_demo:true,outreach_enabled:false};await importOutboundRows([{business_name:'Existing demo',external_customer_id:'fixture-customer',invoice_id:'fixture-invoice',amount_due_cents:10000,status:'unpaid'} as any],false);expect(state.writes.filter(w=>w.table==='outbound_businesses')).toEqual([]);});
 it.each([false,undefined])('rejects name-matched Live or unknown business updates before any writes (%s)',async isDemo=>{state.existing={id:'live',business_name:'Live accounting',is_demo:isDemo,outreach_enabled:false};await expect(importOutboundBusinesses([{business_name:'Live accounting',industry:'elevator_inspection'} as any],false)).rejects.toMatchObject({status:409});expect(state.writes).toEqual([]);});
 it.each([false,undefined])('rejects adding demo invoices to a name-matched Live or unknown business (%s)',async isDemo=>{state.existing={id:'live',business_name:'Live accounting',is_demo:isDemo,outreach_enabled:false};await expect(importOutboundRows([{business_name:'Live accounting',external_customer_id:'fixture',invoice_id:'fixture'} as any],false)).rejects.toMatchObject({status:409});expect(state.writes).toEqual([]);});
});
