import {describe,it,expect} from 'vitest';
import {buildReviewReminder,reviewCalendar,type ReviewSettings} from '../services/outboundReviewRuns';
const settings:ReviewSettings={business_id:'business',stage:'staged_preview',spreadsheet_url:'https://docs.google.com/spreadsheets/d/private-sheet/edit',source_snapshot_at:'2026-09-14T14:17:09Z',enabled:false,reminder_recipient:'operator@example.com',timezone:'America/New_York'};
describe('weekly internal review preparation',()=>{
 it('opens at Tuesday noon New York and uses Monday calendar-week key',()=>{expect(reviewCalendar(new Date('2026-09-15T15:59:59Z')).due).toBe(false);expect(reviewCalendar(new Date('2026-09-15T16:00:00Z'))).toMatchObject({week_start:'2026-09-14',due:true});expect(reviewCalendar(new Date('2026-09-21T03:59:59Z')).week_start).toBe('2026-09-14');expect(reviewCalendar(new Date('2026-09-21T04:00:00Z')).week_start).toBe('2026-09-21');});
 it('retains local noon through winter DST offset',()=>{expect(reviewCalendar(new Date('2026-11-03T16:59:59Z')).due).toBe(false);expect(reviewCalendar(new Date('2026-11-03T17:00:00Z')).due).toBe(true);});
 it('prepares an anchored operator reminder when synchronization is blocked',()=>{const r=buildReviewReminder({businessName:'Pinnacle',settings,connection:{connected:false,stale:true,blockers:['company_binding_not_configured','server_credential_missing']}});expect(r.recipient).toBe('operator@example.com');expect(r.review.invoice_count).toBeNull();expect(r.review.totals_minor_by_currency).toBeNull();expect(r.body_text).toContain('historical preview, not a current balance check');expect(r.review.connection_blockers).toContain('company_binding_not_configured');expect(r.review.sync_triggered).toBe(false);expect(r.review.customer_outreach).toBe(false);});
 it('never presents a staged workbook as live even if another source is connected',()=>{const r=buildReviewReminder({businessName:'Pinnacle',settings,connection:{connected:true,stale:false,blockers:[]},queue:{invoices:[{currency:'USD',source_balance_cents:500}]}});expect(r.review.stage).toBe('blocked_review');expect(r.review.invoice_count).toBeNull();});
 it('groups a verified review by currency without mixing balances',()=>{const r=buildReviewReminder({businessName:'Pinnacle',settings:{...settings,stage:'live_verified',source_snapshot_at:null},connection:{connected:true,stale:false,blockers:[],realm_id:'123',last_successful_sync_at:new Date().toISOString(),spreadsheet_sync:{stale:false,last_sheet_success_at:new Date().toISOString(),source_run_id:'source-run',latest_source_run_id:'source-run'}},queue:{source_run_id:'source-run',invoices:[{currency:'USD',source_balance_cents:1234},{currency:'CAD',source_balance_cents:5678}]}});expect(r.review.totals_minor_by_currency).toEqual({USD:1234,CAD:5678});expect(r.body_text).toContain('USD: 12.34');expect(r.body_text).toContain('CAD: 56.78');});
 it('blocks a supposedly live review when the queue or source is stale',()=>{for(const connection of [{connected:true,stale:true,blockers:[]},{connected:false,stale:false,blockers:['expired_credentials']}]){const r=buildReviewReminder({businessName:'Pinnacle',settings:{...settings,stage:'live_verified'},connection});expect(r.review.stage).toBe('blocked_review');expect(r.review.invoice_count).toBeNull();}});
 it('keeps a failed workbook refresh separate from a successful accounting import',()=>{const r=buildReviewReminder({businessName:'Pinnacle',settings:{...settings,stage:'live_verified',source_snapshot_at:null},connection:{connected:true,stale:false,blockers:[],spreadsheet_sync:{stale:true,last_sheet_success_at:null,failure:'sheet_readback_mismatch'}},queue:{invoices:[{currency:'USD',source_balance_cents:500}]}});expect(r.review.stage).toBe('blocked_review');expect(r.review.invoice_count).toBeNull();expect(r.body_text).toContain('application source is available');expect(r.body_text).toContain('Stale or unverified');expect(r.body_text).toContain('sheet_readback_mismatch');expect(r.review.connection_blockers).toContain('spreadsheet_refresh_stale_or_missing');});
 it('does not claim a workbook is current without stored reconciliation evidence',()=>{const r=buildReviewReminder({businessName:'Pinnacle',settings:{...settings,stage:'live_verified'},connection:{connected:true,stale:false,blockers:[]},queue:{invoices:[]}});expect(r.review.stage).toBe('blocked_review');expect(r.review.spreadsheet_sync.stale).toBe(true);});
 it('fails closed without a privately provisioned single recipient',()=>{for(const recipient of ['', 'one@example.com,two@example.com'])expect(()=>buildReviewReminder({businessName:'Pinnacle',settings:{...settings,reminder_recipient:recipient},connection:{connected:false,stale:true,blockers:[]}})).toThrow(/Approved reminder recipient/);});
 it('requires the workbook and queue to attest the same source snapshot',()=>{
  const connection={connected:true,stale:false,blockers:[],spreadsheet_sync:{stale:false,source_run_id:'older-run',latest_source_run_id:'older-run'}};
  const r=buildReviewReminder({businessName:'Fixture',settings:{...settings,stage:'live_verified'},connection,queue:{source_run_id:'new-run',invoices:[{currency:'USD',source_balance_cents:100}]}});
  expect(r.review.stage).toBe('blocked_review');expect(r.review.connection_blockers).toContain('spreadsheet_source_snapshot_mismatch');expect(r.body_text).not.toContain('Current for the recorded source snapshot');
 });
 it('uses the status paired with the queue rather than an older successful workbook status',()=>{
  const r=buildReviewReminder({businessName:'Fixture',settings:{...settings,stage:'live_verified'},connection:{connected:true,stale:false,blockers:[],spreadsheet_sync:{stale:false,source_run_id:'old',latest_source_run_id:'old'}},queue:{source_run_id:'new',invoices:[],connection:{connected:true,stale:false,blockers:[],spreadsheet_sync:{stale:true,source_run_id:'old',latest_source_run_id:'new',failure:'sheet_pending'}}}});
  expect(r.review.stage).toBe('blocked_review');expect(r.review.spreadsheet_sync.failure).toBe('sheet_pending');expect(r.review.connection_blockers).toContain('spreadsheet_source_snapshot_mismatch');
 });

});
